# Poetry
[tool.poetry]
name = "programming-optimization-assignments"
authors = ["Gabriele Bettineschi <gbettineschi29@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
numpy = "^2.2.3"
pulp = "^3.0.2"
networkx = "^3.4.2"

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
flake8 = "^7.1.2"
flake8-pyproject = "^1.2.3"

# Other
[tool.black]
line-length = 88
target-version = ['py311']

[tool.flake8]
max-line-length = 88
extend-ignore = "E203"